server:
  port: 8082
spring:
  application:
    name: hystris-service
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true
        register: true
    loadbalancer:
      ribbon:
        enabled: false


